// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package topicnotes

import (
	"database/sql"

	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table guaniu_study_topic_notes.
type Entity struct {
	Id              int64       `orm:"id,primary"        json:"id"`                // 编号
	TopicId         int64       `orm:"topic_id"          json:"topic_id"`          // 主题id
	UserId          int64       `orm:"user_id"           json:"user_id"`           // 用户id
	Title       string      `orm:"title"        json:"title"`        // 笔记标题
	Content     string      `orm:"content"      json:"content"`      // 笔记描述
	LikeNum         int         `orm:"like_num"          json:"like_num"`          // 喜欢数
	OrderNum        int         `orm:"order_num"         json:"order_num"`         // 显示顺序
	Status          int         `orm:"status"            json:"status"`            // 是否开放状态（0免费 1 收费  2 只对自己可见 3 只有关注者可见 ）
	CreateOwnerId   int         `orm:"create_owner_id"   json:"create_owner_id"`   // 创建者
	CreateTime      *gtime.Time `orm:"create_time"       json:"create_time"`       // 时间
	ModifyTime      *gtime.Time `orm:"modify_time"       json:"modify_time"`       // 时间
	TopicTableIndex int         `orm:"topic_table_index" json:"topic_table_index"` // 表id 与表topic 相关 
}

type ShowEntity struct {
	Id              int64       `orm:"id,primary"        json:"id"`                // 编号
	TopicId         int64       `orm:"topic_id"          json:"topic_id"`          // 主题id
	UserId          int64       `orm:"user_id"           json:"user_id"`           // 用户id
	Title       string      `orm:"title"        json:"title"`        // 笔记标题
	Content     string      `orm:"content"      json:"content"`      // 笔记描述
	LikeNum         int         `orm:"like_num"          json:"like_num"`          // 喜欢数
	OrderNum        int         `orm:"order_num"         json:"order_num"`         // 显示顺序
	Status          int         `orm:"status"            json:"status"`            // 是否开放状态（0免费 1 收费  2 只对自己可见 3 只有关注者可见 ）
	CreateOwnerId   int         `orm:"create_owner_id"   json:"create_owner_id"`   // 创建者
	CreateTime      *gtime.Time `orm:"create_time"       json:"create_time"`       // 时间
	ModifyTime      *gtime.Time `orm:"modify_time"       json:"modify_time"`       // 时间
	TopicTableIndex int         `orm:"topic_table_index" json:"topic_table_index"` // 表id 与表topic 相关
	Name   string      `orm:"name,omitempty"       json:"name,omitempty"`   // 用户名
	Ext    string      `orm:"ext,omitempty"        json:"ext,omitempty"`    // 扩展字段 
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
// Deprecated.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
// Deprecated.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
// Deprecated.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
// Deprecated.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
// Deprecated.
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
// Deprecated.
func (r *Entity) Update() (result sql.Result, err error) {
	where, args, err := gdb.GetWhereConditionOfStruct(r)
	if err != nil {
		return nil, err
	}
	return Model.Data(r).Where(where, args).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
// Deprecated.
func (r *Entity) Delete() (result sql.Result, err error) {
	where, args, err := gdb.GetWhereConditionOfStruct(r)
	if err != nil {
		return nil, err
	}
	return Model.Where(where, args).Delete()
}
