// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package bookresource

// Fill with you ideas below.
import (
	"github.com/gogf/gf/errors/gerror"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/gtime"
)

// AddReq 用于存储新增请求的请求参数
type AddReq struct {
	BookName        string      `p:"bookName" v:"required#书的名称不能为空"`
	BookAuthor      string      `p:"bookAuthor" `
	BookDesc        string      `p:"bookDesc" `
	BookTags        string      `p:"bookTags" `
	BookCbs         string      `p:"bookCbs" `
	PrintTime       *gtime.Time `p:"printTime" `
	BookIsbn        string      `p:"bookIsbn" `
	Status          int         `p:"status" v:"required#是否开放状态（0正常 1 删除）不能为空"`
	CreateTime      *gtime.Time `p:"createTime" `
	TopicTableIndex int         `p:"topicTableIndex" `
}

// EditReq 用于存储修改请求参数
type EditReq struct {
	Id              int64       `p:"id" v:"required#主键ID不能为空"`
	BookName        string      `p:"bookName" v:"required#书的名称不能为空"`
	BookAuthor      string      `p:"bookAuthor" `
	BookDesc        string      `p:"bookDesc" `
	BookTags        string      `p:"bookTags" `
	BookCbs         string      `p:"bookCbs" `
	PrintTime       *gtime.Time `p:"printTime" `
	BookIsbn        string      `p:"bookIsbn" `
	Status          int         `p:"status" v:"required#是否开放状态（0正常 1 删除）不能为空"`
	TopicTableIndex int         `p:"topicTableIndex" `
}
type RemoveReq struct {
	Ids []int `p:"ids"` //删除id
}

// SelectPageReq 用于存储分页查询的请求参数
type SelectPageReq struct {
	BookName        string      `p:"bookName"`        //书的名称
	BookAuthor      string      `p:"bookAuthor"`      //书的作者
	BookDesc        string      `p:"bookDesc"`        //书的描述
	BookTags        string      `p:"bookTags"`        //书的标签
	BookCbs         string      `p:"bookCbs"`         //出版社
	PrintTime       *gtime.Time `p:"printTime"`       //发行时间
	BookIsbn        string      `p:"bookIsbn"`        //isbn
	Status          int         `p:"status"`          //是否开放状态（0正常 1 删除）
	TopicTableIndex int         `p:"topicTableIndex"` //表id 与表topic 相关
	BeginTime       string      `p:"beginTime"`       //开始时间
	EndTime         string      `p:"endTime"`         //结束时间
	PageNum         int64       `p:"pageNum"`         //当前页码
	PageSize        int         `p:"pageSize"`        //每页数
}

// GetPlugAdByID 根据ID查询记录
func GetByID(id int64) (*Entity, error) {
	entity, err := Model.FindOne(id)
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("根据ID查询记录出错")
	}
	if entity == nil {
		err = gerror.New("根据ID未能查询到记录")
	}
	return entity, nil
}

// AddSave 添加
func AddSave(req *AddReq) error {
	entity := new(Entity)
	//entity.Id = req.Id
	entity.BookName = req.BookName
	entity.BookAuthor = req.BookAuthor
	entity.BookDesc = req.BookDesc
	entity.BookTags = req.BookTags
	entity.BookCbs = req.BookCbs
	entity.PrintTime = req.PrintTime
	entity.BookIsbn = req.BookIsbn
	entity.Status = req.Status
	entity.CreateTime = req.CreateTime
	entity.TopicTableIndex = req.TopicTableIndex
	result, err := Model.Save(entity)
	if err != nil {
		return err
	}
	_, err = result.LastInsertId()
	if err != nil {
		return err
	}
	return nil
}

// 删除
func DeleteByIds(Ids []int) error {
	_, err := Model.Delete("id in(?)", Ids)
	if err != nil {
		g.Log().Error(err)
		return gerror.New("删除失败")
	}
	return nil
}

// 根据ID来修改信息
func EditSave(req *EditReq) error {
	// 先根据ID来查询要修改的记录
	entity, err := GetByID(req.Id)
	if err != nil {
		return err
	}
	// 修改实体
	entity.BookName = req.BookName
	entity.BookAuthor = req.BookAuthor
	entity.BookDesc = req.BookDesc
	entity.BookTags = req.BookTags
	entity.BookCbs = req.BookCbs
	entity.PrintTime = req.PrintTime
	entity.BookIsbn = req.BookIsbn
	entity.Status = req.Status
	entity.TopicTableIndex = req.TopicTableIndex
	_, err = Model.Save(entity)
	if err != nil {
		g.Log().Error(err)
		return gerror.New("修改失败")
	}
	return nil
}

// 分页查询,返回值total总记录数,page当前页
func SelectListByPage(req *SelectPageReq) (total int, page int64, list []*Entity, err error) {
	model := Model
	if req != nil {
		if req.BookName != "" {
			model = model.Where("book_name like ?", "%"+req.BookName+"%")
		}
		if req.BookAuthor != "" {
			model = model.Where("book_author = ?", req.BookAuthor)
		}
		if req.BookDesc != "" {
			model = model.Where("book_desc = ?", req.BookDesc)
		}
		if req.BookTags != "" {
			model = model.Where("book_tags = ?", req.BookTags)
		}
		if req.BookCbs != "" {
			model = model.Where("book_cbs = ?", req.BookCbs)
		}
		if req.BookIsbn != "" {
			model = model.Where("book_isbn = ?", req.BookIsbn)
		}
	}
	// 查询总记录数(总行数)
	total, err = model.Count()
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("获取总记录数失败")
		return
	}
	if req.PageNum == 0 {
		req.PageNum = 1
	}
	page = req.PageNum
	if req.PageSize == 0 {
		req.PageSize = 10
	}
	// 分页排序查询
	list, err = model.Page(int(page), int(req.PageSize)).Order("id asc").All()
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("分页查询失败")
		return
	}
	return
}

// 获取所有数据
func SelectListAll(req *SelectPageReq) (list []*Entity, err error) {
	model := Model
	if req != nil {
		if req.BookName != "" {
			model.Where("book_name like ?", "%"+req.BookName+"%")
		}
		if req.BookAuthor != "" {
			model.Where("book_author = ?", req.BookAuthor)
		}
		if req.BookDesc != "" {
			model.Where("book_desc = ?", req.BookDesc)
		}
		if req.BookTags != "" {
			model.Where("book_tags = ?", req.BookTags)
		}
		if req.BookCbs != "" {
			model.Where("book_cbs = ?", req.BookCbs)
		}
		if req.BookIsbn != "" {
			model.Where("book_isbn = ?", req.BookIsbn)
		}
	}
	// 查询
	list, err = model.Order("id asc").All()
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("查询失败")
		return
	}
	return
}
