// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package topictasks

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table guaniu_study_topic_task.
type Entity struct {
    Id              int64       `orm:"id,primary"        json:"id"`                // 编号                      
    TopicId         int64       `orm:"topic_id"          json:"topic_id"`          // 主题id                    
    TaskTitle       string      `orm:"task_title"        json:"task_title"`        // 任务标题                 
    TimeLine       string      `orm:"time_line"        json:"time_line"`        // 任务截止                  
    TaskContent     string      `orm:"task_content"      json:"task_content"`      // 任务描述                  
    ResourceTypeId  int         `orm:"resource_type_id"  json:"resource_type_id"`  // 关联资源类型，关联字典表  
    BookId          int         `orm:"book_id"           json:"book_id"`           // 书的id                    
    BookCatgoryId   int         `orm:"book_catgory_id"   json:"book_catgory_id"`   // 书的目录id                
    ResourceContent string      `orm:"resource_content"  json:"resource_content"`  // 资源内容                  
    OrderNum        int         `orm:"order_num"         json:"order_num"`         // 显示顺序                  
    CreateTime      *gtime.Time `orm:"create_time"       json:"create_time"`       // 时间                      
    ModifyTime      *gtime.Time `orm:"modify_time"       json:"modify_time"`       // 时间                      
    TopicTableIndex int         `orm:"topic_table_index" json:"topic_table_index"` // 表id 与表topic 相关       
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
// Deprecated.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
// Deprecated.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
// Deprecated.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
// Deprecated.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
// Deprecated.
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
// Deprecated.
func (r *Entity) Update() (result sql.Result, err error) {
	where, args, err := gdb.GetWhereConditionOfStruct(r)
	if err != nil {
		return nil, err
	}
	return Model.Data(r).Where(where, args).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
// Deprecated.
func (r *Entity) Delete() (result sql.Result, err error) {
	where, args, err := gdb.GetWhereConditionOfStruct(r)
	if err != nil {
		return nil, err
	}
	return Model.Where(where, args).Delete()
}