// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package topictasks

// Fill with you ideas below.
import (
	"github.com/gogf/gf/errors/gerror"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/gtime"
)

// AddReq 用于存储新增请求的请求参数
type AddReq struct {
	TopicId         int64       `p:"topicId" `
	TaskTitle       string      `p:"taskTitle" `
	TaskContent     string      `p:"taskContent" `
	ResourceTypeId  int         `p:"resourceTypeId" `         
    TimeLine        string    `p:"timeLine" `  // 任务截止          
	BookId          int         `p:"bookId" `
	BookCatgoryId   int         `p:"bookCatgoryId" `
	ResourceContent string      `p:"resourceContent" `
	OrderNum        int         `p:"orderNum" `
	CreateTime      *gtime.Time `p:"createTime" `
	ModifyTime      *gtime.Time `p:"modifyTime" `
	TopicTableIndex int         `p:"topicTableIndex" `
	NeedVerifyCode int         `p:"needVerifyCode" `
}

// EditReq 用于存储修改请求参数
type EditReq struct {
	Id              int64       `p:"id" v:"required#主键ID不能为空"`
	TopicId         int64       `p:"topicId" `
	TaskTitle       string      `p:"taskTitle" `
	TaskContent     string      `p:"taskContent" `    
    TimeLine        string    `p:"timeLine" `  // 任务截止  
	ResourceTypeId  int         `p:"resourceTypeId" `
	BookId          int         `p:"bookId" `
	BookCatgoryId   int         `p:"bookCatgoryId" `
	ResourceContent string      `p:"resourceContent" `
	OrderNum        int         `p:"orderNum" `
	ModifyTime      *gtime.Time `p:"modifyTime" `
	TopicTableIndex int         `p:"topicTableIndex" `
	NeedVerifyCode int         `p:"needVerifyCode" `
}
type RemoveReq struct {
	Ids []int `p:"ids"` //删除id
}

// SelectPageReq 用于存储分页查询的请求参数
type SelectPageReq struct {
	TopicId         int64       `p:"topicId"`         //主题id
	TaskTitle       string      `p:"taskTitle"`       //任务标题
	TaskContent     string      `p:"taskContent"`     //任务描述
	ResourceTypeId  int         `p:"resourceTypeId"`  //关联资源类型，关联字典表
	BookId          int         `p:"bookId"`          //书的id
	BookCatgoryId   int         `p:"bookCatgoryId"`   //书的目录id
	ResourceContent string      `p:"resourceContent"` //资源内容
	OrderNum        int         `p:"orderNum"`        //显示顺序
	ModifyTime      *gtime.Time `p:"modifyTime"`      //时间
	TopicTableIndex int         `p:"topicTableIndex"` //表id 与表topic 相关
	BeginTime       string      `p:"beginTime"`       //开始时间
	EndTime         string      `p:"endTime"`         //结束时间
	PageNum         int64       `p:"pageNum"`         //当前页码
	PageSize        int         `p:"pageSize"`        //每页数
}

// GetPlugAdByID 根据ID查询记录
func GetByID(id int64) (*Entity, error) {
	entity, err := Model.FindOne(id)
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("根据ID查询记录出错")
	}
	if entity == nil {
		err = gerror.New("根据ID未能查询到记录")
	}
	return entity, nil
}

// AddSave 添加
func AddSave(req *AddReq) error {
	entity := new(Entity)
	//entity.Id = req.Id
	entity.TopicId = req.TopicId
	entity.TimeLine = req.TimeLine
	entity.TaskTitle = req.TaskTitle
	entity.TaskContent = req.TaskContent
	entity.ResourceTypeId = req.ResourceTypeId
	entity.BookId = req.BookId
	entity.BookCatgoryId = req.BookCatgoryId
	entity.ResourceContent = req.ResourceContent
	entity.OrderNum = req.OrderNum
	entity.CreateTime = req.CreateTime
	entity.ModifyTime = req.ModifyTime
	entity.TopicTableIndex = req.TopicTableIndex
	result, err := Model.Save(entity)
	if err != nil {
		return err
	}
	_, err = result.LastInsertId()
	if err != nil {
		return err
	}
	return nil
}

// 删除
func DeleteByIds(Ids []int) error {
	_, err := Model.Delete("id in(?)", Ids)
	if err != nil {
		g.Log().Error(err)
		return gerror.New("删除失败")
	}
	return nil
}

// 根据ID来修改信息
func EditSave(req *EditReq) error {
	// 先根据ID来查询要修改的记录
	entity, err := GetByID(req.Id)
	if err != nil {
		return err
	}
	// 修改实体
	entity.TopicId = req.TopicId
	entity.TaskTitle = req.TaskTitle
	entity.TaskContent = req.TaskContent
	entity.ResourceTypeId = req.ResourceTypeId
	entity.BookId = req.BookId
	entity.TimeLine = req.TimeLine
	entity.BookCatgoryId = req.BookCatgoryId
	entity.ResourceContent = req.ResourceContent
	entity.OrderNum = req.OrderNum
	entity.ModifyTime = req.ModifyTime
	entity.TopicTableIndex = req.TopicTableIndex
	_, err = Model.Save(entity)
	if err != nil {
		g.Log().Error(err)
		return gerror.New("修改失败")
	}
	return nil
}

// 分页查询,返回值total总记录数,page当前页
func SelectListByPage(req *SelectPageReq) (total int, page int64, list []*Entity, err error) {
	model := Model
	if req != nil {
		if req.TaskTitle != "" {
			model = model.Where("task_title = ?", req.TaskTitle)
		} 
		if req.TopicId != 0 {
			model = model.Where("topic_id = ?", req.TopicId)
		}
	}
	// 查询总记录数(总行数)
	total, err = model.Count()
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("获取总记录数失败")
		return
	}
	if req.PageNum == 0 {
		req.PageNum = 1
	}
	page = req.PageNum
	if req.PageSize == 0 {
		req.PageSize = 10
	}
	// 分页排序查询
	list, err = model.Page(int(page), int(req.PageSize)).Order("id asc").Order("order_num desc").All()
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("分页查询失败")
		return
	}
	return
}

// 获取所有数据
func SelectListAll(req *SelectPageReq) (list []*Entity, err error) {
	model := Model
	if req != nil {
		if req.TaskTitle != "" {
			model.Where("task_title = ?", req.TaskTitle)
		}
		if req.TaskContent != "" {
			model.Where("task_content = ?", req.TaskContent)
		}
		if req.ResourceContent != "" {
			model.Where("resource_content = ?", req.ResourceContent)
		}
	}
	// 查询
	list, err = model.Order("id asc").All()
	if err != nil {
		g.Log().Error(err)
		err = gerror.New("查询失败")
		return
	}
	return
}
